import { Account } from "@/types/account";

export const MOCK_ACCOUNTS: Account[] = [
  // --- LEVEL 1 (Locked / Read-Only) ---
  {
    id: "01",
    code: "01",
    name: "ASSETS",
    type: "category",
    parentId: null,
    status: "active",
    currency: "USD",
    accountType: "Bank",
    level: 1,
  },
  {
    id: "02",
    code: "02",
    name: "LIABILITIES",
    type: "category",
    parentId: null,
    status: "active",
    currency: "USD",
    accountType: "Bank",
    level: 1,
  },
  {
    id: "03",
    code: "03",
    name: "CAPITAL",
    type: "category",
    parentId: null,
    status: "active",
    currency: "USD",
    accountType: "Bank",
    level: 1,
  },
  {
    id: "04",
    code: "04",
    name: "REVENUE",
    type: "category",
    parentId: null,
    status: "active",
    currency: "USD",
    accountType: "Bank",
    level: 1,
  },
  {
    id: "05",
    code: "05",
    name: "EXPENSE",
    type: "category",
    parentId: null,
    status: "active",
    currency: "USD",
    accountType: "Bank",
    level: 1,
  },

  // --- LEVEL 2 ---
  {
    id: "0101",
    code: "0101",
    name: "Current Assets",
    type: "category",
    parentId: "01",
    status: "active",
    currency: "USD",
    accountType: "Bank",
    level: 2,
  },
  {
    id: "0102",
    code: "0102",
    name: "Other Assets",
    type: "category",
    parentId: "01",
    status: "active",
    currency: "USD",
    accountType: "Bank",
    level: 2,
  },
  {
    id: "0103",
    code: "0103",
    name: "Fixed Assets",
    type: "category",
    parentId: "01",
    status: "active",
    currency: "USD",
    accountType: "Fixed Asset",
    level: 2,
  },

  // --- LEVEL 3 ---
  {
    id: "010101",
    code: "010101",
    name: "Bank Account",
    type: "account",
    parentId: "0101",
    balance: "$842k",
    status: "active",
    currency: "USD",
    accountType: "Bank",
    level: 3,
    openingBalance: 842000,
  },
  {
    id: "010107",
    code: "010107",
    name: "Inventory",
    type: "account",
    parentId: "0101",
    balance: "$158k",
    status: "active",
    currency: "USD",
    accountType: "Fixed Asset",
    level: 3,
    openingBalance: 158000,
  },

  // --- LEVEL 4 (Max Level) ---
  {
    id: "01010101",
    code: "01010101",
    name: "Petty Cash",
    type: "account",
    parentId: "010101",
    balance: "$500",
    status: "active",
    currency: "USD",
    accountType: "Bank",
    level: 4,
    openingBalance: 500,
  },
];
